# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/controlpanel"
site_name: Progress Telerik Control Panel
# Exclude files that should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,_assetsApi]
exclude_navigation: [knowledge-base/*]
  

navigation: 
## List custom TOC order for folders here
  "FAQ":
          title: "Frequently Asked Questions"
          position: 7

## The application virtual path
baseurl: "/controlpanel"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"




# Feedback Form Google Sheet ID
ff-sheet-id: 6730fe7e-c8d6-4af6-b9aa-00395f10875b

# The google services configuration
google_tag_manager: GTM-6X92
google_analytics: UA-111455-1
gcs_engine: '47b2bdc9d347d46aa'
gcs_api_key: 'AIzaSyC_1zrkB9jMkIDAJ6VBYGilbhOWEFZqQKA'

edit_repo_url: https://github.com/telerik/controlpanel-docs/edit/master
product: "Progress Telerik Control Panel"
product_url: https://www.telerik.com

# Available for names: 
platforms: ["UI for ASP.NET MVC", "UI for ASP.NET AJAX", "UI for Blazor", "UI for WPF", "UI for WinForms", "UI for Silverlight", "UI for Xamarin", "UI for WinUI", "UI for ASP.NET Core", "UI for .NET MAUI"]
# in articles use as shown below: 
# platforms: mvc, ajax, blazor, wpf, winforms, silverlight, xamarin, winui, core, maui
platform: main
download: https://www.telerik.com/download-trial-file/v2-b/devcraft-ultimate
nav:
  "Demos": http://www.telerik.com/support/demos
  "About": http://www.telerik.com/devcraft

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/controlpanel/installing-on-your-computer
-
  title: "Support Resources"
  links: 
    "Documentation": https://docs.telerik.com/controlpanel/introduction
-   
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/telerik-control-panel
    "Blogs": https://www.telerik.com/blogs/.net
    "Control Panel Feedback Portal": https://feedback.telerik.com/controlpanel
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

has_kb_portal: false
has_cta_panels: false
has_api_reference: false

## Do not edit below this line
skip_tabbed_code: true
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..2
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
