name: "BuildAndUploadToTest"

on: 
  workflow_dispatch:
  pull_request:
    branches: 
         - master
jobs:
   build-docs:
     name: build controlpanel documentation
     uses: ./.github/workflows/build_docs.yml
     with:
       branch: ${{ github.ref_name }}
       docs_seed_branch: master
       docs-dest-folder: _site
       jekyll-config: _config.yml
     secrets: inherit

   deploy-documentation-on-test:
     name: deploy documentation to https://testdocs.telerik.com/style-guide/introduction
     needs: build-docs
     uses: ./.github/workflows/deploy_docs.yml
     with:
        CleanProductFolder: '$false'
        DEPLOY_MACHINE_N1: uattkdocsN1.telerik.local
        DEPLOY_MACHINE_N2: uattkdocsN2.telerik.local
        ProductFolderName: controlpanel
        WebAppPoolName: telerikcontrolpanelap
        WebsitesDirectory: C:\Websites
     secrets: inherit
