name: "template | deploy_documentation"

on:
  workflow_call:
    inputs:
      CleanProductFolder:
        description: "Determines whether to clean working dir"
        required: true
        type: string
      DEPLOY_MACHINE_N1:
        description: "Fist Node"
        required: true
        type: string
      DEPLOY_MACHINE_N2:
        description: "Second node"
        required: true
        type: string
      ProductFolderName:
        description: "Documentation folder on the node"
        required: true
        type: string
      WebAppPoolName:
        description: "self explanatory"
        required: true
        type: string
      WebsitesDirectory:
        description: "Path to local work dir on respective node."
        required: true
        type: string

jobs:
  deploy-docs-on-nodes:
    runs-on: [self-hosted, deployDocumentation]
    permissions:
      id-token: write # Required by Akeyless
      contents: write

    steps:

      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN"
            }
          export-secrets-to-environment: false

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: telerik/deployment-scripts
          path: deployment-scripts
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Get site 
        uses: actions/download-artifact@v3.0.2
        with:
          name: site-artifacts
          path: documentation\controlpanel

      - name: Deploy on Node 1
        run: |
           .\DevTools-Deploy.ps1 -ProductFolderName "${{ inputs.ProductFolderName }}" -ZipFileName "site.zip" -WebAppPoolName "${{ inputs.WebAppPoolName }}" -DeployMachineName "${{ inputs.DEPLOY_MACHINE_N1 }}" -DistributionDirectory "${{ github.workspace }}\documentation" -WebsitesDirectory "${{ inputs.WebsitesDirectory }}" -CleanProductFolder ${{ inputs.CleanProductFolder }}
        working-directory: deployment-scripts

      - name: Deploy on Node 2
        run: |
           .\DevTools-Deploy.ps1 -ProductFolderName "${{ inputs.ProductFolderName }}" -ZipFileName "site.zip" -WebAppPoolName "${{ inputs.WebAppPoolName }}" -DeployMachineName "${{ inputs.DEPLOY_MACHINE_N2 }}" -DistributionDirectory "${{ github.workspace }}\documentation" -WebsitesDirectory "${{ inputs.WebsitesDirectory }}" -CleanProductFolder ${{ inputs.CleanProductFolder }}
        working-directory: deployment-scripts

